### PR TITLE
adding support for new functions added in helics 3.3

### PR DESCRIPTION
**Pull request by afisher1**
had to add some additional custom function wrappers for functions added in helics 3.3.

### CODE REVIEW

**Comment by afisher1** [comment]
@phlptp I've corrected the compilation errors in helicsMex.cpp. However buildHelicsInterface.m still fails on my end when copying some files from the v3.3.0 tarball. 
Error in buildHelicsInterface (line 105)
copyfile(fullfile(inputPath,'helics_minimal.h'),fullfile(targetPath,'include','helics_minimal.h'));

**Comment by phlptp** [comment]
What is the error.  The file exists and it works fine on my machine, so not sure what the issue is exactly

**Comment by phlptp** [comment]
huh, the ubuntu tests run to completion now

**Comment by phlptp** [comment]
@afisher1  this is working correctly on my system, and all the tests are passing so I am going to go ahead and merge it and work on some additional docs and instructions, then will tag a release some time this weekend.  

When we get the 3.3.1 release out can you update for that one and we will probably have two releases in a row but that is probably all right

**Review by phlptp — APPROVED** [review]

**Pull request merged**
