### PR TITLE
Feature/octave bindings

### PR DESCRIPTION
**Pull request by phlptp**

### CODE REVIEW

**Comment by phlptp** [comment]
@afisher1 is this able to be merged? or is there more you have to do on this?

**Comment by phlptp** [comment]
@afisher1  you want to finish this up, then I can test and we can try to get it into the 3.6 release version for HELICS and remove the Octave references for that release of HELICS.    Then I can do a bit of work on getting some octave tests running on CI.  But I think finishing this up and getting it merged is the first step.

**Comment by phlptp** [comment]
@afisher1  do we need the buildOctiveHelicsInterfaces.m file any more?

**Comment by phlptp** [comment]
and what versions of octave is this likely to work for?

**Comment by afisher1** [comment]
No. I meant to delete that actually.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by phlptp** [comment]
I will remove it then.  I am going to try to add some tests of octave as well.   If it works with 8.3, I should be able to use the newest ubuntu LTS release for the tests

**Comment by afisher1** [comment]
Yes it should. I suggest having a Matlab test folder and a octave test folder. You will also have an octave friendly version of the startup.m file. It's currently using a function that is not in the octave 8.3. Not sure it's in the 9.4. The function is something like loadlibrary or something like that.

**Comment by phlptp** [comment]
@afisher1 This works with octave 8.4 on WIndows.   Doesn't work with 9.1,  which seems to have to do with a bug in mingw 13.2, not something directly in octave.     There are a couple of the deprecated methods that could be removed and are generating warnings when compiling.   Those will need to be removed at some point.   But I think I am going to merge this and then start working on the tests.   with the mex file in octave the calls are different,  now much more like matlab which is probably a good thing but the tests don't work anymore.    So that will take time.  And I have to set up the build jobs,  which is more complicated such that I didn't want to do it in this PR.   The builds need to be updated as well moving to HELICS 3.6 so it gets intertangled.  Best to deal with that separately.     But this is great and simplifies many thing in supporting octave and matlab!

**Comment by afisher1** [comment]
@phlptp that is great news. FYI those deprecated warnings are occuring in the Matlab mex compilation as well. That will go away when the deprecated functions are removed from the helics.h file. The code that generates the helicMex.cpp file writes a wrapper function for everything present in helics.h.

**Pull request merged**
